### ISSUE TITLE
Publish to maven central repo?

### ISSUE THREAD

**Issue by rolvraen** [nvdb-vegdata/nvdb-api-client#1]
Hi, and thanks for the api-client. 
Since v2 is live, are you planning on publishing the api to the maven central repo soon ?

**Comment by matsandreassen-triona** [comment]
Hey! We're not sure if we'll do that. We have already published it to jCenter, though!

https://bintray.com/nvdb-vegdata/vegdata/nvdb-api-client

**Comment by rolvraen** [comment]
Ok, that will do. Thanks!
