### ISSUE TITLE
Feil lengde for noen segmenter?

### ISSUE THREAD

**Issue by NKAmapper** [nvdb-vegdata/nvdb-api-client#102]
Se på segment 2721409-3-3 her: https://nvdbapiles-v3.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert/2721409?srid=wgs84.

Her er veglenkesekvens/lengde 0.015 (dvs. 1,5 cm), mens veglenkesekvens/geometri/lengde er 12.1854216676429. Den første er mest riktig (selv om start- og slutt-koordinatene i WGS84 er identiske).

Skulle ikke disse to lengde vært (nesten) like?

Et annet eksempel: Segment 3025162-1-4.

**Comment by computerlove** [comment]
Ser ut som veglenka er er splittet opp, men lengde ikke oppdatert.
Det er nok noe som ble innført da geometriegenskaper ble gjort tilgjengelig.

**Comment by johannsl** [comment]
@NKAmapper Denne burde være i orden nå
