### ISSUE TITLE
Dokumentasjonslenker gir 404

### ISSUE THREAD

**Issue by olaven** [nvdb-vegdata/nvdb-api-client#129]
Hei, 

Jeg forsøker å sette meg inn i dette API-et, men alle dokumentasjonslenkene gir 404. Er informasjonen utdatert? Se f.eks. [openapi spec](https://nvdbapiles-v3.atlas.vegvesen.no/dokumentasjon/openapi/), som [indekssiden](https://nvdbapiles-v3.atlas.vegvesen.no/dokumentasjon/) reffererer til. 

Alt godt! 
Olav

**Comment by olaven** [comment]
<img width="822" alt="Scherm­afbeelding 2024-03-09 om 17 53 34" src="https://github.com/nvdb-vegdata/nvdb-api-client/assets/18209665/a4e843be-f07a-48c5-aeb1-26e85daafb5d">

**Comment by AdelsJarlen** [comment]
+1 🙃

**Comment by geirsagberg** [comment]
Det er en del endringer på vei for LES APIet, bl.a. er LES v4 rett rundt hjørnet. Dokumentasjonssiden skal bli ryddet opp i; i mellomtiden kan du finne OpenAPI / Swagger her: https://nvdbapiles.atlas.vegvesen.no/webjars/swagger-ui/index.html, og mer dokumentasjon her: https://nvdb.atlas.vegvesen.no/docs/category/nvdb-api-les

**Comment by geirsagberg** [comment]
V4 er faktisk allerede tilgjengelig, men ikke offentlig lansert enda så kan være noe ustabilt. I v4 er tjenestene separert i større grad; du kan bytte mellom de ulike tjenestene i Swagger øverst til høyre.
Her er f.eks. Vegobjekter-tjenesten i v4: https://nvdbapiles.atlas.vegvesen.no/webjars/swagger-ui/index.html?urls.primaryName=Vegobjekter
Og her er vegnettet: https://nvdbapiles.atlas.vegvesen.no/webjars/swagger-ui/index.html?urls.primaryName=Vegnett

**Comment by olaven** [comment]
> V4 er faktisk allerede tilgjengelig, men ikke offentlig lansert enda så kan være noe ustabilt. I v4 er tjenestene separert i større grad; du kan bytte mellom de ulike tjenestene i Swagger øverst til høyre. Her er f.eks. Vegobjekter-tjenesten i v4: https://nvdbapiles.atlas.vegvesen.no/webjars/swagger-ui/index.html?urls.primaryName=Vegobjekter Og her er vegnettet: https://nvdbapiles.atlas.vegvesen.no/webjars/swagger-ui/index.html?urls.primaryName=Vegnett

Dette er supert, takk skal du ha! 
Jeg ser at [linken](https://nvdbapiles-v3.atlas.vegvesen.no/dokumentasjon/openapi/swagger-ui/index.html) fungerer igjen, og lukker tråden.
