### ISSUE TITLE
Wrong name in enum

### ISSUE THREAD

**Issue by knutimar** [nvdb-vegdata/nvdb-api-client#2]
Hi, for the enum FeatureType.PlacementType there is a wrong name for the value LINE. It says "STREKNING", but it should have been "LINJE".
https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/FeatureType.java#L162

Feature types which are lines get nullable placement types because of this error.

Regards, Knut Imar Hagen

**Comment by matsandreassen** [comment]
Apologies! I have missed your issue for quite some time. I will attempt to have this fixed before Christmas.
