### ISSUE TITLE
Missing featureTypeId in associations

### ISSUE THREAD

**Issue by knutimar** [nvdb-vegdata/nvdb-api-client#3]
When all feature types are retrieved with the function [DatakatalogClient.getFeatureTypes](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/clients/DatakatalogClient.java#L100) with the Include.ALL parameter, the attribute [featureTypeId](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/AssociationType.java#L34) in [AssociationType](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/AssociationType.java) is always null.

When only one feature type is retrieved with the function [DatakatalogClient.getFeatureType](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/clients/DatakatalogClient.java#L117) the attribute [featureTypeId](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/AssociationType.java#L34) in [AssociationType](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/AssociationType.java) is never null.

The attribute [validFrom](https://github.com/nvdb-vegdata/nvdb-api-client/blob/master/src/main/java/no/vegvesen/nvdbapi/client/model/datakatalog/AssociationType.java#L37) is always null when using both of the functions described.

**Comment by matsandreassen** [comment]
Hello!

This is actually an API bug which will be fixed in our next release. 

Thanks for discovering it.

**Comment by computerlove** [comment]
This should be fixed some time a go.
