### ISSUE TITLE
Hvordan henter jeg vegobjekttype kategori?

### ISSUE THREAD

**Issue by podeig** [nvdb-vegdata/nvdb-api-client#4]
Hei, 
I Java applikasjon "Datakatalog" alle veggobjekter er delt i kategorier. Hvordan henter jeg kategoriene i APIen? Hvordan kan jeg hente objekter som er knyttet kun til en bestemt kategori?
Takk! :)

**Comment by computerlove** [comment]
APIet støtter ikke dette akkurat nå. 
Den funksjonaliteten du beskriver er implementert og delvis rullet ut. Det vil si endepunktene eksisterer, men dataene er ikke på plass.

Kategoriene vil være å finne på https://www.vegvesen.no/nvdb/api/v2/vegobjekttyper/kategorier 
Da vil du kunne be om vegobjekttyper i den bestemte kategorien med https://www.vegvesen.no/nvdb/api/v2/vegobjekttyper?kategori=kategori-id

Oppdaterer saken når dette er mulig.

**Comment by podeig** [comment]
Takk for svaret! Det er fint at det blir implementert. Setter pris på om denne saken blir oppdatert når dere har dette på plass :)

**Comment by computerlove** [comment]
Nå er kategoriene på plass. Det er ikke alltid ting går så kjapt i SVV :)

**Comment by podeig** [comment]
Takk for svaret! Ting tar tid :-)
