### ISSUE TITLE
unøyaktighet for oppslag på posisjon

### ISSUE THREAD

**Issue by arve0** [nvdb-vegdata/nvdb-api-client#61]
Ser ut som det er unøyaktighet i oppslag på posisjon, både i API les v2 og v3. Hadde ventet å få kryssystem med søk på posisjonen til `EV18 S2D1 m8909 KD3 m10`:

```sh
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/veg?vegsystemreferanse=EV18S2D1m8909KD3m10" --silent | jq .geometri.wkt
"POINT Z(303991.385 6605302.555 191.121)"
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=303991.385&nord=6605302.555" --silent | jq .[0].vegsystemreferanse.kortform
"EV18 S2D1 m9207" <---- Hadde forventet å få "EV18 S2D1 m8909 KD3 m10"
```

Oppslaget gir kun ett treff:
```sh
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=303991.385&nord=6605302.555" --silent | jq '. | length'
1
```

Litt lenger bort på kryssystemet, meterverdi 20, fungerer fint.

En kan detektere feilen ved å se at posisjon returnert er flyttet 2.5 meter unna posisjonen som det ble søkt på:
```sh
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=303991.385&nord=6605302.555" --silent | jq .[0].geometri.wkt
"POINT Z(303991.603 6605305.065 191.446)"
```

**Comment by arve0** [comment]
Er tilsvarende for WSG84:

```sh
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/veg?vegsystemreferanse=EV18S2D1m8909KD3m10&srid=4326" --silent | jq .geometri.wkt
"POINT Z(59.54003893 11.53286687 191.12122914)"
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?lat=59.54003893&lon=11.53286687&srid=4326" --silent | jq .[0].vegsystemreferanse.kortform
"EV18 S2D1 m9207"
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?lat=59.54003893&lon=11.53286687&srid=4326" --silent | jq .[0].geometri.wkt
"POINT Z(59.54006153 11.53286841 191.44639375)"
```

**Comment by arve0** [comment]
Oppslaget gir flere treff dersom en gir `maks_antall=10`, men treffet på kryssdelen er 10 meter unna.

```sh
curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=303991.385&nord=6605302.555&maks_antall=10"
```

Svar:
```json
[
  {
    "vegsystemreferanse": {
      "vegsystem": {
        "id": 941417675,
        "versjon": 1,
        "vegkategori": "E",
        "fase": "V",
        "nummer": 18
      },
      "strekning": {
        "id": 942723174,
        "versjon": 1,
        "strekning": 2,
        "delstrekning": 1,
        "arm": false,
        "adskilte_løp": "Nei",
        "trafikantgruppe": "K",
        "meter": 9207.418,
        "retning": "MED"
      },
      "kortform": "EV18 S2D1 m9207"
    },
    "veglenkesekvens": {
      "veglenkesekvensid": 971358,
      "relativPosisjon": 0.98664,
      "kortform": "0.98664@971358"
    },
    "geometri": {
      "wkt": "POINT Z(303991.603 6605305.065 191.446)",
      "srid": 6173
    },
    "avstand": 3,
    "kommune": 3014
  },
  {
    "vegsystemreferanse": {
      "vegsystem": {
        "id": 941417712,
        "versjon": 1,
        "vegkategori": "E",
        "fase": "V",
        "nummer": 18
      },
      "strekning": {
        "id": 942723174,
        "versjon": 1,
        "strekning": 2,
        "delstrekning": 1,
        "arm": false,
        "adskilte_løp": "Nei",
        "trafikantgruppe": "K",
        "meter": 8909,
        "retning": "MED"
      },
      "kryssystem": {
        "id": 943759296,
        "versjon": 1,
        "kryssystem": 1000,
        "kryssdel": 2,
        "meter": 300.279,
        "retning": "MED",
        "trafikantgruppe": "K"
      },
      "kortform": "EV18 S2D1 m8909 KD2 m300"
    },
    "veglenkesekvens": {
      "veglenkesekvensid": 971370,
      "relativPosisjon": 0.75455,
      "kortform": "0.75455@971370"
    },
    "geometri": {
      "wkt": "POINT Z(303992.091 6605310.346 191.499)",
      "srid": 6173
    },
    "avstand": 8,
    "kommune": 3014
  },
  {
    "vegsystemreferanse": {
      "vegsystem": {
        "id": 941417712,
        "versjon": 1,
        "vegkategori": "E",
        "fase": "V",
        "nummer": 18
      },
      "strekning": {
        "id": 942723174,
        "versjon": 1,
        "strekning": 2,
        "delstrekning": 1,
        "arm": false,
        "adskilte_løp": "Nei",
        "trafikantgruppe": "K",
        "meter": 8909,
        "retning": "MED"
      },
      "kryssystem": {
        "id": 943759296,
        "versjon": 1,
        "kryssystem": 1000,
        "kryssdel": 3,
        "meter": 20,
        "retning": "MED",
        "trafikantgruppe": "K"
      },
      "kortform": "EV18 S2D1 m8909 KD3 m20"
    },
    "veglenkesekvens": {
      "veglenkesekvensid": 971371,
      "relativPosisjon": 0.06551,
      "kortform": "0.06551@971371"
    },
    "geometri": {
      "wkt": "POINT Z(304000.9 6605299.6 191.1)",
      "srid": 6173
    },
    "avstand": 10,
    "kommune": 3014
  },
  {
    "vegsystemreferanse": {
      "vegsystem": {
        "id": 941417675,
        "versjon": 1,
        "vegkategori": "E",
        "fase": "V",
        "nummer": 18
      },
      "strekning": {
        "id": 942723175,
        "versjon": 1,
        "strekning": 2,
        "delstrekning": 1,
        "arm": false,
        "adskilte_løp": "Nei",
        "trafikantgruppe": "K",
        "meter": 9217,
        "retning": "MED"
      },
      "kortform": "EV18 S2D1 m9217"
    },
    "veglenkesekvens": {
      "veglenkesekvensid": 971358,
      "relativPosisjon": 0.98783,
      "kortform": "0.98783@971358"
    },
    "geometri": {
      "wkt": "POINT Z(303982 6605305.9 191.4)",
      "srid": 6173
    },
    "avstand": 10,
    "kommune": 3014
  }
]
```

Hadde forventet at tredje svar, _EV18 S2D1 m8909 KD3 m20_, var med meterverdi 10.

**Comment by krimjo** [comment]
0-20m er en konnekteringslenke, prøv å legge på "&konnekteringslenker=true" slik: https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=303991.385&nord=6605302.555&konnekteringslenker=true

**Comment by arve0** [comment]
Takk for svar. Var ikke klar over `konnekteringslenker`. Fra [_Nasjonalt vegreferansesystem_](https://www.vegvesen.no/_attachment/61505):

> 5.3. Konnekteringslenker
I noen tilfeller er ikke senterlinjene naturlig knyttet sammen i et nettverk. For eksempel vil dette være kobling mellom to veger der kryssområdet fysisk hører til den ene vegen, forlengelsen av et svingefelt som beskriver en kjørebevegelse midt i et kryss, eller kobling av en gangveg til kjørevegen der det er naturlig at veglenkene skal være koblet sammen for å danne et nettverk. I slike tilfeller benyttes konnekteringslenker. Disse lenkene eksisterer kun for å knytte sammen andre veglenker. For at det skal bli sammenheng mellom veglenkene for den vegen som ikke eier arealet, forlenges veglenken over krysset, og for den overlappende strekningen benyttes konnekteringslenke. Figur 25 viser hvordan konnekteringslenker brukes i kryss.

**Comment by arve0** [comment]
Jeg var litt rask, ser ikke ut som jeg får ønsket resultat for punkt som ligger i kryss:

```
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/veg?vegsystemreferanse=FV2402s1d1m0" --silent | jq .geometri.wkt
"POINT Z (262111.188 6744592.504 266.42)"
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=262111.188&nord=6744592.504&konnekteringslenker=true&maks_antall=10" --silent | jq "map(.vegsystemreferanse.kortform)"
[
  "FV2368 S2D1 m1530",
  "FV2402 S1D1 m3",
  "FV2368 S2D20 m1557",
  "FV2368 S2D20 m1558",
  "FV2368 S2D20 m1554",
  "FV2368 S2D20 m1563"
]
```

Dersom jeg definerer hvilken veg jeg ønsker, får jeg konnekteringslenken også:
```
$ curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=262111.188&nord=6744592.504&konnekteringslenker=true&maks_antall=10&vegsystemreferanse=fv2402" --silent | jq "map(.vegsystemreferanse.kortform)"
[
  "FV2402 S1D1 m0",
  "FV2402 S1D1 m3",
  "FV2402 S1D1 m12"
]
```

**Comment by krimjo** [comment]
Vi har en åpen feil på noe tilsvarende, så godt mulig det løser dette problemet. Jeg har lagt inn dette tilfellet i saken.

**Comment by arve0** [comment]
@krimjo Har du et saksnummer, slik at vi kan referere feilen til vår systemeier?

Har observert en tilsvarende feil, der svar mangler treff, men der treff veksler sporadisk:

```bash
for i in $(seq 10); do 
    curl "https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?srid=6173&konnekteringslenker=true&maks_antall=5&maks_avstand=30&nord=7598944.76&ost=571096.65" --silent | jq "map(.vegsystemreferanse.kortform)"
    sleep 0.1
done
```

**Hva var forventet?**
Svar med to treff, FV7556 og KV3016.

**Hva skjer?**
Svar med ett treff, vekslende mellom FV7556 og KV3016. 10 kall er som oftes tilstrekkelig for å se vekslingen:
```json
[
  "FV7556 S1D1 m366"
]
[
  "KV3016 S1D1 m1683"
]
[
  "FV7556 S1D1 m366"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
[
  "KV3016 S1D1 m1683"
]
```

**Hvilke miljø?**
✅ OK: https://apilesv3.utv.atlas.vegvesen.no/
❌ Feil: https://apilesv3-stm.utv.atlas.vegvesen.no/, https://apilesv3.test.atlas.vegvesen.no/ og https://apilesv3.atlas.vegvesen.no/

**Comment by krimjo** [comment]
Det med at svar veksler skal være fikset og på vei ut. Den andre saken med at konnekteringslenke mangler har nummer NVDB-4804 og er ikke påbegynt enda

**Comment by arve0** [comment]
Hei! Når kan fiks forventes i apilesv3.test.atlas.vegvesen.no? Feilen observeres fortsatt i apilesv3-stm.utv.atlas.vegvesen.no, som jeg antar er neste miljø etter apilesv3.utv.atlas.vegvesen.no?

**Comment by krimjo** [comment]
Ikke helt sikker på når, men den blir med på neste release. Det som ligger i apilesv3.utv.atlas.vegvesen.no er snapshot av det som blir med på neste release. Det kommer i https://apilesv3.test.atlas.vegvesen.no/ når vi releaser, og sannsynligvis i https://apilesv3-stm.utv.atlas.vegvesen.no/ også da.

**Comment by arve0** [comment]
Hei! Noen oppdatering på denne? Feilen kan fortsatt reproduseres i `-stm`, `test` og produksjon.

**Comment by krimjo** [comment]
Hei, ja, saken er påbegynt for litt siden ser jeg, så antar den snart er ferdig. Da vil den komme til stm i første omgang.

**Comment by torkie** [comment]
Når det gjelder sak NVDB-4804, ser det ut til å være i orden nå.  Den første lenka (https://apilesv3-stm.utv.atlas.vegvesen.no/posisjon?ost=262111.188&nord=6744592.504&konnekteringslenker=true&maks_antall=10) gir blant annet ut denne posisjonen:

`<posisjon>
<vegsystemreferanse>
<vegsystem>
<id>1002139935</id>
<versjon>1</versjon>
<vegkategori>F</vegkategori>
<fase>V</fase>
<nummer>2402</nummer>
</vegsystem>
<strekning>
<id>1003446462</id>
<versjon>1</versjon>
<strekning>1</strekning>
<delstrekning>1</delstrekning>
<arm>false</arm>
<adskilte_løp>Nei</adskilte_løp>
<trafikantgruppe>K</trafikantgruppe>
<meter>0.0</meter>
<retning>MED</retning>
</strekning>
<kortform>FV2402 S1D1 m0</kortform>
</vegsystemreferanse>
<veglenkesekvens>`

Denne posisjonen er på ei konnekteringslenke (jeg har klippa bort det som ikke er relevant):

`NVDB.NN_REFLINK_OT(1060309, NULL, 50002, 
	NVDB.NN_PORTS_OT(
		NVDB.NN_PORT_OT(1, 1102759, 1, 50001, 0), 
		NVDB.NN_PORT_OT(18, 3038051, 1, 50001, 0.00115448)
	), 
	NULL, 
	NVDB.NN_REFLINKPARTS_OT(
		NVDB.NN_CONNECTIONREFLINKPART_OT('1950-01-01 00:00:00.0', NULL, 19, 2, 18, 3407, 4, NVDB.NF_SPATIALATTRIBUTE_OT(500002, NULL, MDSYS.SDO_GEOMETRY(3006, 82347, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 0, 1, 17, 2, 1), MDSYS.SDO_ORDINATE_ARRAY(20190430, 3.87373205069625, 8, 1, 24, -1, 30, -1, 99, -1, 3, 2, 7001, 3, 5, 3407, 259127.93, 6743665.03, 383.64, 259124.72, 6743662.87, 383.83))), '2002-09-01 00:00:00.0', 2, 4, 2, NULL, NULL)
	), 
	4340.33192247689, 
	1
)`

Ser det greit ut?

**Comment by arve0** [comment]
> Når det gjelder sak NVDB-4804 ... Ser det greit ut?

Ja, det ser bra ut for `apilesv3-stm.utv` og `apilesv3.utv`. Når kan vi forvente endringen i test og produksjon?

Når det gjelde vekslende svar, ser jeg fortsatt samme problematikk. Er det noen framgang der? Har den et annet saksnummer?

**Comment by krimjo** [comment]
NVDB-4804 skal fungere i test og prod også, det er samme versjon av api-et der (2019.17.0)

Vekslende svar, hvis det fortsatt er problemer skal vi se mer på det, har laget egen sak på det: NVDB-4981

**Comment by arve0** [comment]
> NVDB-4804 skal fungere i test og prod også

Det stemmer ikke for test, om det ikke er NVDB-4981 som tuller?

```sh
$ curl "https://apilesv3.test.atlas.vegvesen.no/posisjon?ost=262111.188&nord=6744592.504&konnekteringslenker=true&maks_antall=3" --silent | jq "map(.vegsystemreferanse.kortform)"
[
  "FV2368 S2D1 m1530",
  "FV2402 S1D1 m3",
  "FV2368 S2D20 m1557"
]
$ curl "https://apilesv3.atlas.vegvesen.no/posisjon?ost=262111.188&nord=6744592.504&konnekteringslenker=true&maks_antall=3" --silent | jq "map(.vegsystemreferanse.kortform)"
[
  "FV2402 S1D1 m0",
  "FV2402 S1D1 m3",
  "FV2368 S2D20 m1557"
]
```

Mener jeg så det samme i produksjon for to timer siden.

**Comment by arve0** [comment]
> om det ikke er NVDB-4981 som tuller?

Flere forespørsler viser seg at det vekslende resultat.

**Comment by tormoseng** [comment]
Angående vekslende resultater. Kunne du ha testet vår neste leveransekandidat på https://www.utv.vegvesen.no/nvdb/api/v3/posisjon?srid=6173&konnekteringslenker=true&maks_antall=5&maks_avstand=30&nord=7598944.76&ost=571096.65

https://apilesv3.utv.atlas.vegvesen.no/ skal også være oppdatert, men ikke https://apilesv3-stm.utv.atlas.vegvesen.no/ (hvor du fortsatt kan se vekslende resultat)

**Comment by arve0** [comment]
Får ikke vekslende, men får nå feil resultat. Kun `FV7556 S1D1 m366`, konnekteringslenken for `KV3016` er ikke med.

**Merk**: Jeg har ikke opplevd feilen i UTV-miljøet, så dette er en forverring, [se opprinnelig kommentar](https://github.com/nvdb-vegdata/nvdb-api-client/issues/61#issuecomment-559372453).

**Comment by arve0** [comment]
@tormoseng Noen oppdatering?

**Comment by torkie** [comment]
Jeg ser på saken, så det kommer nok en oppdatering snart.

**Comment by tormoseng** [comment]
@arve0 Du kan teste nå på
https://www.utv.vegvesen.no/nvdb/api/v3/posisjon?srid=6173&konnekteringslenker=true&maks_antall=5&maks_avstand=30&nord=7598944.76&ost=571096.65

**Comment by arve0** [comment]
Ser ut som den "doble" er 7 cm unna på vegen 

```
                "meter": 366.379,
                "meter": 366.45,
```

seks millimeter i avstandsdifferanse til sendt punkt

```
        "avstand": 0.032,
        "avstand": 0.038,
```

men ellers lik.

Dobbelt svar er ikke noen krise for oss, men det kan være tegn på at jeg har misforstått noe eller at dere har en logikkfeil som dere ønsker fikse.

Ønsker dere spesielt at det testes mot www.utv.vegvesen.no? Ikke atlas-miljøene?

**Comment by computerlove** [comment]
Du har nok ikke misforstått noe. Jeg tror vi kan forbedre hvordan dette virker.
Slik det virker nå er at gitt koordinat:
* finn segmenter innenfor radius
* Beregn avstand mellom punkt og segmentets geometri
* Finn veglenkesekvensposisjon og meterverdi for punktet

Så de to er nok `"referanse": "885726-4-4"` og 
`"referanse": "885726-29-4"` på https://apilesv3.utv.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert/885726.json

Skal lage en sak på å gi ut kun ett resultat for en strekningsdel.

www.utv.vegvegsen.no/nvdb/api/v3 er det samme som apilesv3.utv.atlas..
pm1.utv.vegvegsen.no/nvdb/api/v3 er det samme som apilesv3-stm.utv.atlas.. 
Atlas-varianten er ikke den offisielle ennå, men har håp om at den blir det, slik at de andre miljøene blir borte.
Jeg vil gjerne at atlas brukes så mye som mulig, men det er alltid samme versjon som kjører, så i praksis har det ikke noe å si.

**Comment by arve0** [comment]
Takk for hjelpen🙂 Lukker saken.
