### ISSUE TITLE
Hvordan kan man hente vegreferanser for flere broer via en request?

### ISSUE THREAD

**Issue by alina-lapina** [nvdb-vegdata/nvdb-api-client#7]

**Comment by vegvesen-brase** [comment]
For å finne alle broer:

https://www.vegvesen.no/nvdb/api/v2/vegobjekter/60

For å filtrere ut hvilke du vil ha, se:

http://api.vegdata.no/endepunkt/vegobjekter.html

Under "avgrens søkeresultatet": du kan filtrere på område (fylke, kommune, kontraktsområde, mm)

For å få med vegreferanse i listevisningen, bruk inkluderparameteren, (samme lenke som over, se velg respons) inkluder=lokasjon gir deg vegreferansene:

https://www.vegvesen.no/nvdb/api/v2/vegobjekter/60?inkluder=lokasjon
