### ISSUE TITLE
Mangler "medium" i segmentert vegnett

### ISSUE THREAD

**Issue by NKAmapper** [nvdb-vegdata/nvdb-api-client#75]
Dokumentasjonen i https://nvdbapilesv3.docs.apiary.io/#reference/0/segmentert-vegnett/segmenter-for-veglenkesekvens angir at det segmenterte vegnettet skal eksponere Medium. Medium er imidlertid ikke inkludert i les-api v3 per i dag.

Medium var med i det segmenterte vegnettet i les-api v2. Utfordringer med stedfesting av broer og underganger gjør at Medium ikke kan hentes inn via vegobjekter. Medium er med i det usegmenterte vegnettet (veglenkesekvenser) og kan flettes inn derfra, men det er en kostbar løsning som medfører dobbelt lasting av alle veglenker.

Fint om Medium kunne tas med i det segmenterte vegnettet.

**Comment by computerlove** [comment]
Har lenket til denne siden i saken vi allerede har i intern jira for inkludering av geometri-egenskaper på segmentert vegnett

**Comment by NKAmapper** [comment]
Flott, dette var bare for å ha et sted å følge opp/få tilbakemelding.

**Comment by computerlove** [comment]
Denne er på vei ut. Tilgjengelig på https://nvdbapiles-v3.utv.atlas.vegvesen.no nuh
