### ISSUE TITLE
Noen segmenter har sluttposisjon før startposisjon

### ISSUE THREAD

**Issue by NKAmapper** [nvdb-vegdata/nvdb-api-client#76]
Det finnes noen få segmenter i det segmenterte vegnettet i api-les v3 som har sluttposisjon før startposisjon. De medfører problemer ved fletting av vegobjekter.

Det er f.eks. tre stk i Trondheim: 3141465-1-5, 3141466-1-5 og 3113846-1-4.

**Comment by computerlove** [comment]
Vi tolker det som at det er superstedfestingen du påpeker er feil.
https://nvdbapiles-v3.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert/3141466.json har to segmenter med 
```json
"superstedfesting": {
   "veglenkesekvensid": 42881,
   "startposisjon": 0.80577115,
   "sluttposisjon": 0.82851178,
   "retning": "MOT",
   "sideposisjon": "0",
   "kjørefelt": [
      "1"
   ]
}
```
og 
```json
"superstedfesting": {
   "veglenkesekvensid": 42881,
   "startposisjon": 0.82851178,
   "sluttposisjon": 0.80577115,
   "retning": "MOT",
   "sideposisjon": "0",
   "kjørefelt": [
      "1"
   ]
}
```

Dette er nå rettet: https://nvdbapiles-v3.utv.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert/3141466.json

**Comment by NKAmapper** [comment]
Fint, men dette er nok en mer generell feil som finnes en god del andre steder også. For eksempel disse segmentene i Klepp kommune:
3168190-1-2
3168190-2-2
3168190-4-2
3168191-1-2
3168191-2-2
3168191-3-2

**Comment by computerlove** [comment]
Skal høre med Vegnettsgruppa om det er feil.

**Comment by computerlove** [comment]
Når jeg ser på de siste eksemplene ser det ut som de er i orden. Finner du ennå slike?

**Comment by NKAmapper** [comment]
Nei, de kom ofte tidligere, men har ikke sett på en stund nå.

**Comment by computerlove** [comment]
Ok. Det har blitt kjørt endel script siden mars, så kan hende noe er rettet. Bare å åpne saken igjen om det observeres igjen :)
