### ISSUE TITLE
Svært korte segmenter

### ISSUE THREAD

**Issue by NKAmapper** [nvdb-vegdata/nvdb-api-client#78]
Det segmenterte vegnettet i api-les v3 inneholder en del svært korte segmenter, ofte bare noen centimeter eller rundt en meter lange. Mye tyder på at de er klippet feil, som om klippingen såvidt bommet på neste segment. En del av disse segmentene har en unormal vinkel til nabosegmentene. De finnes i alle kommuner ser det ut til, f.eks. 9 stk i Grimstad, 72 stk Trondheim osv.

Disse segmentene skaper noen problemer ved fletting av vegobjekter inn i vegnettet fordi start/sluttnode blir liggende for nær hverandre.

Eksempler:
2264914-6-13 (4 cm)
2442974-1-10 (21 cm)
22312-3-17 (47 cm)
1707381-5-6 (89 cm)

**Comment by computerlove** [comment]
Kan du sjekke dette på nytt? (gjerne mot https://nvdbapiles-v3.utv. også)

Har ikke sjekket alle eksemplene, men 1707381 ser ikke feil ut
Segmentet på 89cm oppstår fordi det er en overgang på `0.95278685@1707381` mellom Strekning (916) 1003449073 og 1003449074

Hva er det som har en unormal vinkel? 
```
0.95229044-0.95278685@1707381 (0.95246929-0.95296374@1707378) LINESTRING Z(122404.215 6483471.053 45.98, 122404.178 6483470.102 45.974)
0.95278685-0.99725794@1707381 (0.95296374-0.99725894@1707378) LINESTRING Z(122404.178 6483470.102 45.974, ..., 122399.46 6483384.97 45.54)
0.99725794-1.0@1707381        (0.99725894-1.0@1707378       ) LINESTRING Z(122399.46 6483384.97 45.484, ..., 122399.03 6483379.73 45.464)
```
ser jo ut til å henge sammen

**Comment by NKAmapper** [comment]
Eksemplene stemmer, også i UTV, men jeg ser at delstrekning har endret seg siden saken ble opprettet. Delstrekning er i tillegg forskjellig i PROD og UTV nå. Her er de samme segmentene angitt med relative posisjoner:

0.99199948-0.99203081@2264914 (4 cm)
0.44645934-0.45361797@2442974 (22 cm)
0.54058672-0.5554839@22312 (53 cm)
0.95229044-0.95278685@1707381 (95 cm)

Og noen flere eksempler:

0.05785124-0.05833333@1707380 (6 cm)
0.44646061-0.44981289@2442973 (10 cm)
0.51996836-0.52621558@22489 (22 cm)

Problemet her er ikke at de ikke henger sammen, men at de er meningsløst korte.

Vinkel: Se bildet under for et eksempel. Dette er det første eksemplet ovenfor fra 2264914 som er 4 cm. E18 ligger som en pen jevn linje både før og etter, men akkurat i dette segmentet skapes det rare vinkler. Dette var bare tenkt som et symptom på at noe har gått galt.

<img width="615" alt="Skjermbilde 2020-05-27 kl  07 41 18" src="https://user-images.githubusercontent.com/35384359/82982006-8d01ea80-9fed-11ea-9a07-adc5191d7e52.png">

**Comment by computerlove** [comment]
Det er nok bare en konsekvens av de underliggende data.
Forskjellene på `0.99199948-0.99203081` og `0.99203081-1.0` ser ut til å være et kontraktsområde.

Geometrien for den veglenken som er i bunn her er kun to punkter, som blir til tre punkter på grunn av segmentet `0.99199948-0.99203081`. 

Du bryr deg vel ikke om kontraktsområder og riksvegruter, så kanskje du burde slå sammen segmenter som skiller seg kun i disse.
