### ISSUE TITLE
Manglende støtte for å kombinere veglenke-ID og parametere for segmenterte veglenkesekvenser

### ISSUE THREAD

**Issue by daniesso** [nvdb-vegdata/nvdb-api-client#92]
Trenger å konsumere `/vegnett/veglenkesekvenser/segmentert/{veglenkesekvensid}`-endepunktet med request parameters. SegmentedRoadNetClient-klienten støtter tilsynelatende å enten spesifisere `veglenkesekvensid`, eller parametere (vha RoadNetRequest), men ikke begge deler.

Kan jeg komme med en PR på dette?

**Comment by computerlove** [comment]
Jepp, PR i vei!
